name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_FIREBASE_CREDENTIALS }}'
    
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: 'Use gcloud CLI'
      run: 'gcloud config get project'
    - name: 'Use gcloud CLI'
      run: 'gcloud auth list'


    - name: 'Use gcloud CLI'
      # run: 'gcloud info'
      run: 'gcloud firebase test android run --app app/build/outputs/apk/debug/app-debug.apk --type robo --device model=MediumPhone.arm,version=30,locale=en,orientation=portrait'